### ISSUE TITLE
robust_asr

### ISSUE THREAD

**Issue by ximzzzzz** [raotnameh/E2E_NER-Through-Speech#10]
hello 
i was interested in your paper for robust asr
but lately you've closed your repository. 
something happend?

**Comment by raotnameh** [comment]
@ximzzzzz Hi, nothing happened. We will make the repo public soon.

 Also, in the future, it would be better if you could email the first author mentioned in the paper regarding any Robust_asr paper/code related issues.

**Comment by ximzzzzz** [comment]
hello Hemant Yadav

thanks for reply.

i have another question.

in your paper, how long it took to train your model?

i tried to same architecture with different dataset, but after 1 days of
training, it is still stupid.... :(


Best Regards
ethan Kim
ximzzzzz@gmail.com

2021년 1월 1일 (금) 오전 2:32, Hemant Yadav <notifications@github.com>님이 작성:

**Comment by raotnameh** [comment]
@ximzzzzz Can you email me at hemantya@iiitd.ac.in with the issue? I would be happy to reply there.

I will share the training plots with you. That would give you the idea of convergence. Also, it takes longer to converge compared to training a standard ASR. 

I have a question fo rhow many epochs have you trained the architecture?
