### ISSUE TITLE
Issue in identifying CUDA device

### ISSUE THREAD

**Issue by kavya2425** [raotnameh/E2E_NER-Through-Speech#11]
Hi,
I have installed all the requirements and everything was successful. while executing the train.py script i am facing the following issue. I am having P1000 GPU with CUDA-10.1 on it.
Kindly help!!
Thank in advance!!

**python train.py --train-manifest data/ner/train.csv --val-manifest data/ner/dev.csv --cuda  --rnn-type gru --hidden-layers 5 --momentum 0.95 --weights models/without_space.pth --opt-level O0 --loss-scale 1.0 --hidden-size 1024 --epochs 50 --lr 0.0051 --gpu-rank 4 --batch-size 32 --labels star_labels.json**
_**

_**THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    torch.cuda.set_device(int(args.gpu_rank))
  File "/home/server2/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:59**_

**_

**Comment by raotnameh** [comment]
Hi, how many gpu do you have on the machine? 
Try setting the --gpu-rank to 0 instead of 4.  
@kavya2425

**Comment by kavya2425** [comment]
Thanks so much, its working with 0. I have only one gpu.
