### ISSUE TITLE
check failed. Invalid language model path

### ISSUE THREAD

**Issue by FriedaSmith** [raotnameh/E2E_NER-Through-Speech#3]
Hello. I have a error.
Using  language model:[http://www.openslr.org/resources/11/4-gram.arpa.gz](http://www.openslr.org/resources/11/4-gram.arpa.gz) 
python3 test.py --test-manifest data/ner/dev.csv --model-path models/without_space.pth --batch-size 64 --decoder beam --beam-width 800 --alpha .96 --beta 4 --lm-path lm/4_gram.arpa
`[ctcdecode/src/scorer.cpp:57] FATAL: "(access(filename, 0)) == (0)" check failed. Invalid language model path`

**Comment by raotnameh** [comment]
Hi @FriedaSmith, As the exception says "the language model path is invalid" means either there is no file at that location or it is not an .arpa file.
We have added a language model in the lm directory. Try using the language model at lm/lm.binary. It should work for you.
Let me know if it does not work.

**Comment by FriedaSmith** [comment]
Thank you. I mistakenly wrote `lm/4-gram` as `lm/4_gram`. Sorry to bother you.
