### ISSUE TITLE
Add possibility to get time frame of each word

### ISSUE THREAD

**Issue by gbaril** [raotnameh/E2E_NER-Through-Speech#5]
This is not an issue, but more an idea to improve the code. It would be nice to have a parameter allowing us to show/hide the time frame of each word in the output.

Current output:
`MY NAME IS |GEORGE] AND I LIVE IN $NEW YORK]`

An example of my idea: 
`MY*0.1-0.25* NAME*0.3-0.7* IS*0.75-0.9* |GEORGE*0.9-1.4*] AND*1.5-1.8* I*1.8-1.9* LIVE*1.95-2.3* IN*2.3-2.4* $NEW*2.45-2.86* YORK*2.9-3.1*]`

Another way of doing it:
`MY 0.1 0.25 \n
NAME 0.3 0.7\n
IS 0.75 0.9\n
|GEORGE] 0.9 1.4\n
AND 1.5 1.8\n
I 1.8 1.9\n
LIVE 1.95 2.3\n
IN 2.3 2.4\n
$NEW 2.45 2.86\n
YORK] 2.9 3.1`

Thank you!

**Comment by raotnameh** [comment]
Hi, @gbaril I will try to add this functionality as soon as I can. Thanks, for the suggestion.

**Comment by raotnameh** [comment]
Hi @gbaril I have added the option to print the time stamp of each word in the transcibe.py script. Please pass the --offsets argument as shown in the command below.

To run the transcribe.py: 
> python transcribe.py --offsets --model-path models/without_space.pth --audio-path test.wav --lm-path lm/lm.binary --alpha 0.96 --beta 0.4 --beam-width 2048 --decoder beam
 
The output should look like this:

> Total duration of the audio file is : 4.464 seconds.
>  <0.74>|ANITA]<1.24>   <1.34>PASSED<1.61>   <1.75>OUT<1.83>   <2.05>DURING<2.19>   <2.29>GYMNASTICS<2.83>   <2.83>SHE<3.21>   <3.27>RECOVERED<3.67>   <3.75>QUICKL<4.01>
> 

To change the output format you can make changes in this [function](https://github.com/raotnameh/End-to-end-E2E-Named-Entity-Recognition-from-English-Speech/blob/a0b7c9745eae8b2225d93d7de0d0cabdc56d08f1/E2E_NER/transcribe.py#L65) or create your own function.

I'm also adding a dummy test.wav file that you can use.

Let me know if you have any doubts. I hope it helps.

**Comment by gbaril** [comment]
Thank you ! It is perfect :)
